name: bip39_mnemonic
description: Mnemonic code for generating deterministic keys a.k.a. BIP39.
version: 3.0.8
homepage: https://github.com/ethicnology/dart-bip39-mnemonic

environment:
  sdk: '>=2.17.0 <4.0.0'
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
  convert: ^3.1.2
dependencies:
  pointycastle: ">=3.0.0 <5.0.0"
  unorm_dart: ^0.3.0
