name: bip39_mnemonic
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/ethicnology/dart-bip39-mnemonic

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  pointycastle: ^3.5.2
