name: bip39_mnemonic
description: Mnemonic code for generating deterministic keys a.k.a. BIP39.
version: 3.0.6
homepage: https://github.com/ethicnology/dart-bip39-mnemonic

environment:
  sdk: ">=2.17.0 <3.0.0"
dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  convert: ^3.1.1
dependencies:
  pointycastle: ^3.7.0
  unorm_dart: ^0.2.0
